export function getRandomWords(): string[] {
    let words: string[] = [];

    for (let i = 0; i <= 9; i++) {
        const randomIndex = Math.floor(Math.random() * 209)

        words.push(
            wordList[randomIndex]
        )

    }
    return words
}

const wordList: string[] = [
    "Casa",
    "Escola",
    "Hospital",
    "Igreja",
    "Praia",
    "Parque",
    "Rua",
    "Cidade",
    "Campo",
    "Floresta",
    "Rio",
    "Mar",
    "Sol",
    "Lua",
    "Estrela",
    "Céu",
    "Chuva",
    "Vento",
    "Fogo",
    "Água",
    "Terra",
    "Montanha",
    "Areia",
    "Pedra",
    "Árvore",
    "Flor",
    "Grama",
    "Fruta",
    "Legume",
    "Carne",
    "Pão",
    "Leite",
    "Queijo",
    "Arroz",
    "Feijão",
    "Macarrão",
    "Bolo",
    "Doce",
    "Café",
    "Suco",
    "Mesa",
    "Cadeira",
    "Cama",
    "Porta",
    "Janela",
    "Telhado",
    "Chão",
    "Parede",
    "Espelho",
    "Relógio",
    "Celular",
    "Computador",
    "Televisão",
    "Livro",
    "Caneta",
    "Lápis",
    "Borracha",
    "Mochila",
    "Sapato",
    "Camisa",
    "Calça",
    "Jaqueta",
    "Chapéu",
    "Óculos",
    "Bolsa",
    "Dinheiro",
    "Moeda",
    "Carteira",
    "Chave",
    "Carro",
    "Ônibus",
    "Trem",
    "Avião",
    "Barco",
    "Bicicleta",
    "Moto",
    "Estrada",
    "Ponte",
    "Semáforo",
    "Praça pública",
    "Parque infantil",
    "Posto de gasolina",
    "Shopping center",
    "Supermercado",
    "Padaria",
    "Farmácia",
    "Delegacia",
    "Prefeitura",
    "Rodoviária",
    "Aeroporto",
    "Sala de aula",
    "Quadra esportiva",
    "Campo de futebol",
    "Piscina",
    "Academia",
    "Banheiro",
    "Cozinha",
    "Quarto",
    "Sala de estar",
    "Mesa de jantar",
    "Cadeira de escritório",
    "Cama de casal",
    "Escova de dentes",
    "Pasta de dente",
    "Papel higiênico",
    "Toalha de banho",
    "Sabonete",
    "Shampoo",
    "Condicionador",
    "Espelho grande",
    "Relógio de parede",
    "Telefone celular",
    "Computador pessoal",
    "Controle remoto",
    "Ventilador de teto",
    "Ar-condicionado",
    "Geladeira",
    "Fogão",
    "Micro-ondas",
    "Panela",
    "Prato",
    "Copo",
    "Talheres",
    "Faca de cozinha",
    "Garfo de mesa",
    "Colher de sopa",
    "Garrafa de água",
    "Copo de vidro",
    "Caixa de papelão",
    "Sacola plástica",
    "Saco de lixo",
    "Lixeira",
    "Vassoura",
    "Rodo",
    "Pano de chão",
    "Balde",
    "Produto de limpeza",
    "Sabão em pó",
    "Detergente",
    "Esponja de cozinha",
    "Máquina de lavar",
    "Varal de roupas",
    "Ferro de passar",
    "Tábua de passar",
    "Tomada elétrica",
    "Interruptor",
    "Lâmpada",
    "Fio elétrico",
    "Carregador",
    "Bateria",
    "Internet",
    "Rede social",
    "Aplicativo",
    "Mensagem de texto",
    "Chamada de vídeo",
    "Conta bancária",
    "Cartão de crédito",
    "Caixa eletrônico",
    "Senha",
    "Documento",
    "Carteira de identidade",
    "Carteira de motorista",
    "Passaporte",
    "Certidão de nascimento",
    "Bilhete",
    "Ingresso",
    "Fila",
    "Atendimento",
    "Consulta médica",
    "Exame de sangue",
    "Remédio",
    "Receita médica",
    "Vacina",
    "Dor de cabeça",
    "Febre",
    "Resfriado",
    "Almoço",
    "Café da manhã",
    "Jantar",
    "Lanche da tarde",
    "Hora do descanso",
    "Dia de trabalho",
    "Fim de semana",
    "Férias",
    "Viagem",
    "Passeio",
    "Turismo",
    "Hotel",
    "Quarto de hotel",
    "Reserva",
    "Check-in",
    "Bagagem",
    "Mala",
    "Mapa",
    "Guia turístico"
];

